
version: 2

sources:
  - name: staging
    description: Staging schema
    database: dw_flights
    tables:
      - name: airlines
      - name: airports
      - name: planes
      - name: weather
      - name: flights

  - name: raw_data
    description: DW raw data
    schema: raw_data
    database: dw_flights
    tables:
      - name: airlines
        description: Airlines
        columns:
          - name: carrier
            description: Airline code
            tests:
              - unique
              - not_null
          - name: name
            description: Airline name
            tests:
              - not_null

      - name: airports
        description: Airports
        columns:
          - name: faa
            description: Airport FAA code
            tests:
              - unique
              - not_null
          - name: name
            description: Airport name
            tests:
              - not_null
          - name: latitude
            tests:
              - not_null
          - name: longitude
            tests:
              - not_null
          - name: altitude
            tests:
              - not_null
          - name: timezone
            tests:
              - not_null
          - name: dst
            tests:
              - not_null
          - name: timezone_name
            tests:
              - not_null

      - name: flights
        description: Flights history
        columns:
          - name: carrier
            tests:
              - relationships:
                    to: source('raw_data', 'airlines')
                    field: carrier
          - name: flight
            tests:
              - not_null
          - name: year
            tests:
              - not_null
          - name: month
            tests:
              - not_null
          - name: day
            tests:
              - not_null
          - name: hour
            tests:
              - not_null
          - name: minute
            tests:
              - not_null
          - name: actual_dep_time
          - name: schedule_dep_time
          - name: dep_delay
          - name: actual_arr_time
          - name: sched_arr_time
          - name: arr_delay
          - name: tailnum
            tests:
              - not_null
              - relationships:
                  to: source('raw_data', 'planes')
                  field: tailnum
          - name: origin
            tests:
              - not_null
              - relationships:
                  to: source('raw_data', 'airports')
                  field: faa
          - name: dest
            tests:
              - not_null
              - relationships:
                  to: source('raw_data', 'airports')
                  field: faa
          - name: air_time
            tests:
              - not_null
          - name: distance
            tests:
              - not_null
          - name: time_hour
            tests:
              - not_null

      - name: planes
        description: Planes
        columns:
          - name: tailnum
            description: Plane tailnum identifier
            tests:
              - unique
              - not_null
          - name: year
            description: Plane built year
          - name: type
            tests:
              - not_null
          - name: manufacturer
            tests:
              - not_null
          - name: model
            tests:
              - not_null
          - name: engines
            tests:
              - not_null
          - name: seats
            tests:
              - not_null
          - name: speed
          - name: engine
            tests:
              - not_null